# we use a pre-build docker image instead of a Dockerfile, because we can pre-fetch that onto Gitpod infrastructure.
image: meysholdt/applitools-dev-environment:latest
ports:

  # open up the port for VNC
  - port: 6080
    onOpen: open-preview

  # ignore all other ports
  - port: 1-6079
    onOpen: ignore
  - port: 6081-65534
    onOpen: ignore
tasks:

# in 'init' we can have bash-code that is executed during the pre-build.
# We also run 'mvn test' without actually running the tests to ensure all dependencies are fetched.
# in 'command' we have bash-code that is executen in the Gitpod Terminal View when the user opens a workspace.
- init: |
    mvn install
    mvn test -Dtest=\!CBasicDemo -DfailIfNoTests=false
  command: |
    mvn test -Dtest=BasicDemo